"""Deterministic natural-language composer for fishing-log embedding input.

The output of `compose_fishing_log_embedding_text` is fed verbatim into the
Gemini ``embed_content`` API (model ``gemini-embedding-001``). Determinism
matters: the same row must produce byte-identical text on every invocation so
a future migration can detect "vector is stale because the row changed"
reliably.

Bumping the template (re-ordering, adding fields, changing labels) requires
bumping `EMBEDDING_TEXT_VERSION`. Part 2 will use that constant to filter out
vectors generated by older templates during similarity search.
"""

from __future__ import annotations

EMBEDDING_TEXT_VERSION: int = 1
"""Schema version of the natural-language template emitted by this module."""

MAX_EMBEDDING_NOTES_CHARS: int = 2000
"""Hard upper bound on `notes` length before truncation."""

_TRUNCATION_MARKER: str = "…(truncated)"


def _format_optional_float(value: float | None) -> str:
    """Render a nullable float for the embedding template (`n/a` if absent)."""

    if value is None:
        return "n/a"
    return repr(value)


def _format_notes(notes: str) -> str:
    """Trim notes to `MAX_EMBEDDING_NOTES_CHARS`, appending a marker if cut."""

    if len(notes) <= MAX_EMBEDDING_NOTES_CHARS:
        return notes
    return notes[:MAX_EMBEDDING_NOTES_CHARS] + _TRUNCATION_MARKER


def compose_fishing_log_embedding_text(
    *,
    fishing_location: str,
    fishing_scene: str,
    target_species: str,
    water_depth_m: float,
    lure_type: str,
    lure_color: str,
    retrieve_speed: str,
    caught_count: int,
    weight_lb: float | None,
    length_cm: float | None,
    temperature_c: float,
    wind_speed_ms: float,
    pressure_hpa: int,
    condition_code: str,
    notes: str,
) -> str:
    """Render a fixed-order, single-string representation of a fishing log."""

    weight_text = _format_optional_float(weight_lb)
    length_text = _format_optional_float(length_cm)
    notes_text = _format_notes(notes)

    return (
        "FishSniper fishing log.\n"
        f"Location: {fishing_location}.\n"
        f"Scene: {fishing_scene}.\n"
        f"Target species: {target_species}.\n"
        f"Depth meters: {repr(water_depth_m)}.\n"
        f"Lure: {lure_type} / {lure_color}. Retrieve: {retrieve_speed}.\n"
        f"Catch: count {caught_count}, weight_lb {weight_text}, length_cm {length_text}.\n"
        "Weather: "
        f"temp_c {repr(temperature_c)}, wind_ms {repr(wind_speed_ms)}, "
        f"pressure_hpa {pressure_hpa}, condition {condition_code}.\n"
        f"Notes: {notes_text}."
    )
