"""Pydantic models for authentication."""

from pydantic import BaseModel, Field


class LoginResponseBody(BaseModel):
    """Response containing a JWT after successful login."""

    access_token: str = Field(
        description="Bearer token to authorize subsequent API calls.",
    )
    is_new_user: bool = Field(
        description="True when this login created a new `users` row for the email.",
    )


class AuthErrorResponseBody(BaseModel):
    """Standard error payload for auth failures."""

    error: str = Field(description="Short error message suitable for display or logging.")


class GoogleOAuthExchangeRequestBody(BaseModel):
    """Authorization-code exchange payload posted from the SPA's Google callback page."""

    code: str = Field(
        min_length=1,
        description="Authorization code returned by Google to the SPA redirect URI.",
    )
    code_verifier: str = Field(
        min_length=1,
        description="PKCE code verifier originally generated by the SPA before redirect.",
    )
    redirect_uri: str = Field(
        min_length=1,
        description=(
            "Redirect URI used during Google authorize step. Must match an entry in "
            "GOOGLE_OAUTH_ALLOWED_REDIRECT_URIS exactly."
        ),
    )
